Seed
decidim-archive/docs-features pull request #1
Opened 2017-10-21 16:00 UTC by xabier

@zuzust I finished. Have a look at the result. I think we are still missing the main functional arquitecture diagram. I will upload soon

2017-10-21 16:01 UTC, zuzust commented
Deploy preview ready!

Built with commit d557426e76bfd3d82175e001dad1868e13ea56c9

https://deploy-preview-1--decidim-features.netlify.com

2017-10-23 10:08 UTC, zuzust requested changes
You should complete three more tasks before merging your contribution:

1) You should add the catalan version in your PR as well.
2) You should normalize the text before first heading in {ca,es,en}/README.md (aka Metadata) in all three versions (they are different at the moment).
3) You should restore contents of {en,es}/book.json. They are metadata used by gitbook.

Ping me back if you've got any doubts.

2017-10-23 16:26 UTC, xabier commented
>You should add the catalan version in your PR as well.

DONE

> You should normalize the text before first heading in {ca,es,en}/README.md (aka Metadata) in all three versions (they are different at the moment).

DONE

> You should restore contents of {en,es}/book.json. They are metadata used by gitbook.

DONE (but sure it is ok!)

2017-10-24 09:59 UTC, zuzust approved these changes

2017-10-24 10:00 UTC, merged